# Generated by Django 3.2.25 on 2024-11-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='after_sale_status',
            field=models.CharField(choices=[('none', '无售后'), ('requested', '申请售后'), ('processing', '售后处理中'), ('approved', '售后通过'), ('rejected', '售后被拒绝'), ('completed', '售后完成')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('pending_shipment', '待发货'), ('pending_receipt', '待收货'), ('pending_review', '待评价'), ('completed', '已完成'), ('canceled', '已取消'), ('9', '退货/售后')], default='0', max_length=20),
        ),
    ]
