# Generated by Django 3.2.25 on 2024-11-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20241112_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('pending_shipment', '待发货'), ('pending_receipt', '待收货'), ('pending_review', '待评价'), ('completed', '已完成'), ('canceled', '已取消'), ('9', '退货/售后')], default='pending_payment', max_length=20),
        ),
    ]
