# Generated by Django 3.2.25 on 2024-11-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('pending_shipment', '待发货'), ('pending_receipt', '待收货'), ('pending_review', '待评价'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_payment', max_length=20),
        ),
    ]
