# Generated by Django 3.2.25 on 2024-11-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
