# Generated by Django 3.2.25 on 2024-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_auto_20241105_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='产地名称')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '茶叶产地',
                'verbose_name_plural': '茶叶产地',
                'ordering': ['name'],
            },
        ),
    ]
