# Generated by Django 3.2.25 on 2024-11-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.origin'),
        ),
    ]
