# Generated by Django 3.2.25 on 2024-11-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='促销活动名称')),
                ('promotion_type', models.CharField(choices=[('discount', '打折'), ('full_reduction', '满减'), ('buy_gift', '买赠')], max_length=20, verbose_name='促销类型')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='折扣(如0.8代表8折)')),
                ('full_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='满减条件金额')),
                ('reduction_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='满减金额')),
                ('buy_quantity', models.IntegerField(blank=True, null=True, verbose_name='买赠条件数量')),
                ('gift_quantity', models.IntegerField(blank=True, null=True, verbose_name='赠送数量')),
                ('start_time', models.DateTimeField(verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(verbose_name='活动结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('allow_stack', models.BooleanField(default=False, verbose_name='是否允许叠加')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.promotion', verbose_name='促销活动'),
        ),
    ]
