# Generated by Django 3.2.25 on 2025-03-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_auto_20241116_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['start_time'], 'verbose_name': '促销活动', 'verbose_name_plural': '促销活动'},
        ),
    ]
