"""
Django settings for tea_sales_system project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6d+x7_#0s#=9sh=^5*=(kem50a4_hfja_8u=(*-fwh0p@-6^3u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sales_system',
    'order_management',
    'user_management',
    'product_management.apps.ProductManagementConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTHENTICATION_BACKENDS = (
    'user_management.backends.CustomAuthBackend',  # 确保路径正确
    'django.contrib.auth.backends.ModelBackend',  # 保留默认的 ModelBackend
)
ROOT_URLCONF = 'tea_sales_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sales_system.context_processors.cart_item_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'tea_sales_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',    # 数据库引擎
        'NAME': 'tea_sales_system',            # 数据库名称
        'USER': 'root',                 # 数据库用户名
        'PASSWORD': 'jiandande123.',             # 数据库密码
        'HOST': 'localhost',                     # 数据库主机，默认本地为 'localhost'
        'PORT': '3306',                          # MySQL 端口，默认3306
        'OPTIONS': {
            'charset': 'utf8mb4',                # 可选项，设置字符集为utf8mb4
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

# settings.py
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},  # 设置密码最小长度
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 默认语言为简体中文

LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', 'Simplified Chinese'),
    # 可以添加其他语言
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # 确保这里有你的翻译文件夹
]


TIME_ZONE = 'Asia/Shanghai'
USE_TZ = True

USE_I18N = True

USE_L10N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'static'),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CART_SESSION_ID = 'cart'
LOGIN_REDIRECT_URL = 'home'   # 登录成功后的页面URL名称
LOGOUT_REDIRECT_URL = 'login'  # 退出登录后的页面URL名称
CSRF_COOKIE_SECURE = False
AUTH_USER_MODEL = 'user_management.User'

ALIPAY = {
    'appid': '2021004199682528',
    'app_notify_url': '127.0.0.1:8000',  # 支付宝支付回调 URL
    'app_private_key_path': 'C:/Work/Ali_Pay_Public_Key_RSA2048.txt',
    'alipay_public_key_path': 'C:/Work/App_Private_Key_RSA2048.txt',
    'sign_type': 'RSA2',  # 或者 RSA
}

